### ISSUE TITLE
SCL SDA pin change

### ISSUE THREAD

**Issue by paulplpl** [rambo/TinyWire#10]
Hi Rambo, 

I tied using your library with standard pins (PA4, PA6) on Attiny84. Works like charm! However, those pins are already in use by the SPI interface. I tried changing the I2C pins to PA3 and PA2 in usiTwiSlave.c as: 

'#if defined(__AVR_ATtiny84__)
.....
'#  define PORT_USI_SDA        PORTA3 // was PORTA6 SDA
'#  define PORT_USI_SCL        PORTA2 //was PORTA4 SCL
'#  define PIN_USI_SDA         PINA3  //was PINA6 SDA
'#  define PIN_USI_SCL         PINA2  //was PINA4 SCL
.....
and the communication broke down. Can they be changed? I guess my bitmasks might be wrong...

Thanks, 
Paul

**Comment by ravipr72** [comment]
Hi Rambo,
I needed 4 PWM pins on 84 and one of them happens to be SDA pin used by TinyWireS. Is there a way to change TinyWireS to use a different pin?
thanks,
ravi

**Comment by rambo** [comment]
I don't think so, it uses the USI peripheral so whatever pins that uses you're stuck with, unless you go with some library that has bit-banged I2C slave implementation (I don't know of one).
