### ISSUE TITLE
Attiny master-slave I2C communication

### ISSUE THREAD

**Issue by shomar80** [rambo/TinyWire#11]
Hi Rambo,

I am not sure if I am posting this in the correct place, so I would appreciate if you can take a look?

I have started a question where I am trying to establish communication between attiny 85 master and 2 attiny85 slaves using your library, the details are here: http://forum.arduino.cc/index.php?topic=255543.0

I hope you can help me in finding where and what I am doing wrong?

Thanks

**Comment by ravipr72** [comment]
Hi Rambo,
I am trying to use TinyWire{S,M} on attiny45@8Mhz  and it does'nt seem to work. I have modified the example code to just react to request from Master. Is there any known issue here?
It seems to work fine if I use Arduino (Wire) as either Master or Slave.

**Comment by rambo** [comment]
Probably TinyWireM cannot deal with "clock-stretching" (neither will raspberry pi, btw), ATMega328 (in Arduino) has proper hardware I2C so in  slave mode it does not stretch the clock (if you don't do much, but you shouldn't) and in master mode it can handle clock-streching by the slave.

**Comment by ravipr72** [comment]
Thanks for the reply. I really appreciate. Note that if I replace either of Master or Slave with ATMega328, it seems to work. is that expected as well?

**Comment by rambo** [comment]
Yes, in slave mode atmega328 will not stretch the clock (unless you do something incredibly stupid in the interrupt) and in master mode it can handle clock stretching correctly.

ATTiny1634 in theory has proper hardware support for I2C slave (but not master), but I have not yet had the time to update this library to support that.

**Comment by ravipr72** [comment]
BTW, changing the Slave to 16Mhz and master to 8Mhz makes it work quite
well. basically Slave has to be faster than the master so that Master does
not resort to clock stretching.

**Comment by rambo** [comment]
It's the slave that does the clock-streching, not master. But yeah, if the slave is fast enough (for whatever reason) then there is no need to stretch the clock. You could also just lower the I2C communication speed (since the bus is synchronously clocked by the master it doesn't really matter if you're using "nonstandard" speed as long as the master can generate that clock).

**Comment by ravipr72** [comment]
Thanks and sorry for bugging you (again). How do I lower the I2C speed? I
tried chaning the F_CPU and SYS_CLK in TinyWireM, but do not recall it made
any difference. Will try again if thats the way to slow it down.

**Comment by ravipr72** [comment]
I meant that if Slave is faster and will not do clock stretching, master
will not have to handle the clock stretching scenario - basically I picked
it up from your old email to me on this topic !
