### ISSUE TITLE
Header file

### ISSUE THREAD

**Issue by ind03** [rambo/TinyWire#29]
I like header files like that usiTwiSlave.h !
void    usiTwiSlaveInit( uint8_t );

So everybody knows what to pass in.
Where is the effort to use:
void    usiTwiSlaveInit( uint8_t address);
???

**Comment by rambo** [comment]
I do not understand the question, `usiTwiXxx` functions are internal anyway https://github.com/rambo/TinyWire/blob/master/TinyWireS/examples/attiny85_i2c_slave/attiny85_i2c_slave.ino#L134 shows the correct way to setup device.
