### ISSUE TITLE
ATTiny x61 PORTA functionality

### ISSUE THREAD

**Issue by gilphilbert** [rambo/TinyWire#52]
The ATTinyx61 devices (261, 461, 861) support two USIs, one on PORTB (as defined) and one on PORTA. The pin configuration is essentially the same, just on the other port.

Do you have any suggestions on how to get this working? I tried a quick change in the library, swapping PORTB definitions for PORTA but the device doesn't appear on the I2c bus.

Thanks!

**Comment by rambo** [comment]
no ideas, sorry.

**Comment by gilphilbert** [comment]
Oh well

Switched to AVR and used the usitwislave library instead - the PORTA functionality works well.
